languge: node.js
node.js: 
  - 10.16.3
cache: 
  directories:
  - node_modules
install:
  - npm install
before_script:
  script:
  - npm run build
  after_script: 
  - cd ./dist
  - git init
  - git config user.name "dalianmaoQAQ"
  - git config user.email "1570714177@qq.com"
  - git add .
  - git commit -m "Travis CI builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:deploy
  - ssh root@121.4.26.210 'cd /data/www && git fetch --all && git reset --hard origin/deploy && git pull'
branches:
  only:
  - master
